/* ============================================================
   dbo.Products.Seed.sql
   Seeds all Products (Hawa Cafeteria menu).
   Self-contained: resolves its own category IDs at the top,
   runs as a single batch with one INSERT.
   ============================================================ */

DECLARE @FoodId INT = (
    SELECT CategoryId FROM Categories
    WHERE Name = N'Food' AND ParentCategoryId IS NULL
);

DECLARE @ManakeeshId  INT = (SELECT CategoryId FROM Categories WHERE Name = N'Manakeesh (مناقيش)'  AND ParentCategoryId = @FoodId);
DECLARE @FatayerId    INT = (SELECT CategoryId FROM Categories WHERE Name = N'Fatayer (فطائر)'    AND ParentCategoryId = @FoodId);
DECLARE @PizzaId      INT = (SELECT CategoryId FROM Categories WHERE Name = N'Pizza (بيتزا)'      AND ParentCategoryId = @FoodId);
DECLARE @ShakhtouraId INT = (SELECT CategoryId FROM Categories WHERE Name = N'Shakhtoura (شختورة)' AND ParentCategoryId = @FoodId);
DECLARE @FarshouhaId  INT = (SELECT CategoryId FROM Categories WHERE Name = N'Farshouha (فرشوحة)'  AND ParentCategoryId = @FoodId);
DECLARE @JuicesId2    INT = (SELECT CategoryId FROM Categories WHERE Name = N'Juices (عصائر)');

INSERT INTO Products
    (Name, CategoryId, Description, UnitPrice, TaxRateId, IsActive)
VALUES
    /* ---- Manakeesh (مناقيش) ---- */
    (N'Zater (زعتر) - Large',  @ManakeeshId, N'Manakeesh Large', 6.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Zater (زعتر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Zater & Olives (زعتر مع زيتون) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Zater & Olives (زعتر مع زيتون) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Meat (لحمة) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Meat (لحمة) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese (جبنة) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese (جبنة) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Meat (جبن مع لحم) - Large',  @ManakeeshId, N'Manakeesh Large', 8.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Meat (جبن مع لحم) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Zater (جبن مع زعتر) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Zater (جبن مع زعتر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Baraka (جبن مع حبة البركة) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Baraka (جبن مع حبة البركة) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. (جبن مع خضار) - Large',  @ManakeeshId, N'Manakeesh Large', 8.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. (جبن مع خضار) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Muhamar (جبن محمر) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Muhamar (جبن محمر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Egg (جبن مع بيض) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Egg (جبن مع بيض) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Chicken (جبن مع دجاج) - Large',  @ManakeeshId, N'Manakeesh Large', 9.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Chicken (جبن مع دجاج) - Small',  @ManakeeshId, N'Manakeesh Small', 5.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Olives (جبن مع زيتون) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Olives (جبن مع زيتون) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Mashrom (جبن مع مشروم) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Mashrom (جبن مع مشروم) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Hotdog (جبن مع نقانق) - Large',  @ManakeeshId, N'Manakeesh Large', 8.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Hotdog (جبن مع نقانق) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Labna (جبن مع لبنة) - Large',  @ManakeeshId, N'Manakeesh Large', 8.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Labna (جبن مع لبنة) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Honey (جبن مع عسل) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Honey (جبن مع عسل) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Sabanek (جبن مع سبانخ) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Sabanek (جبن مع سبانخ) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. & Hotdog (جبن مع خضار و نقانق) - Large',  @ManakeeshId, N'Manakeesh Large', 9.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. & Hotdog (جبن مع خضار و نقانق) - Small',  @ManakeeshId, N'Manakeesh Small', 5.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Oman (جبن بطاطس عمان) - Large',  @ManakeeshId, N'Manakeesh Large', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Oman (جبن بطاطس عمان) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Sabanek (سبانخ) - Large',  @ManakeeshId, N'Manakeesh Large', 6.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Sabanek (سبانخ) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Muhamar (محمر) - Large',  @ManakeeshId, N'Manakeesh Large', 6.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Muhamar (محمر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna (لبنة) - Large',  @ManakeeshId, N'Manakeesh Large', 6.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna (لبنة) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Olives (لبنة مع زيتون) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Olives (لبنة مع زيتون) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Honey (لبنة مع عسل) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Honey (لبنة مع عسل) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Zater (لبنة مع زعتر) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Zater (لبنة مع زعتر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Muhamar (لبنة مع محمر) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Muhamar (لبنة مع محمر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Mashrom (لبنة مع مشروم) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Mashrom (لبنة مع مشروم) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Falafel (لبنة مع فلافل) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Falafel (لبنة مع فلافل) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Hotdog (لبنة مع نقانق) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Hotdog (لبنة مع نقانق) - Small',  @ManakeeshId, N'Manakeesh Small', 5.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft (كرافت) - Large',  @ManakeeshId, N'Manakeesh Large', 6.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft (كرافت) - Small',  @ManakeeshId, N'Manakeesh Small', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Zater (كرافت زعتر) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Zater (كرافت زعتر) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Honey (كرافت عسل) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Honey (كرافت عسل) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Olives (كرافت زيتون) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Olives (كرافت زيتون) - Small',  @ManakeeshId, N'Manakeesh Small', 4.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Hotdog (كرافت نقانق) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Hotdog (كرافت نقانق) - Small',  @ManakeeshId, N'Manakeesh Small', 5.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Chicken (كرافت دجاج) - Large',  @ManakeeshId, N'Manakeesh Large', 9.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Chicken (كرافت دجاج) - Small',  @ManakeeshId, N'Manakeesh Small', 5.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Muhamar (كرافت محمر) - Large',  @ManakeeshId, N'Manakeesh Large', 7.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kraft & Muhamar (كرافت محمر) - Small',  @ManakeeshId, N'Manakeesh Small', 5.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),

    /* ---- Fatayer (فطائر) ---- */
    (N'Meat Fatayer (لحم)',  @FatayerId, N'Fatayer per piece', 1.75, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Fatayer (جبن)',  @FatayerId, N'Fatayer per piece', 1.75, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Zater Fatayer (زعتر)',  @FatayerId, N'Fatayer per piece', 1.75, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Muhamar Fatayer (محمر)',  @FatayerId, N'Fatayer per piece', 1.75, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Sabanek Fatayer (سبانخ)',  @FatayerId, N'Fatayer per piece', 1.75, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Onion Fatayer (بصل)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pizza Fatayer (بيتزا)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pizza & Chicken Fatayer (بيتزا مع دجاج)',  @FatayerId, N'Fatayer per piece', 2.75, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Baraka Fatayer (جبن مع حبة البركة)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Zater Fatayer (جبن مع زعتر)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Olives Fatayer (لبنة مع زيتون)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Zater Fatayer (لبنة مع زعتر)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labna & Falafel Fatayer (لبنة مع فلافل)',  @FatayerId, N'Fatayer per piece', 2.25, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Kibbeh Maqli (كبة مقلي)',  @FatayerId, N'Fatayer per piece', 2.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Sambosa Vegetable (سمبوسة خضار)',  @FatayerId, N'Fatayer per piece', 2.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),

    /* ---- Pizza (بيتزا) ---- */
    (N'Meat Pizza (لحم) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Meat Pizza (لحم) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Meat Pizza (لحم) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Meat Pizza (لحم) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Pizza (جبن) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Pizza (جبن) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Pizza (جبن) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Pizza (جبن) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Meat Pizza (جبن مع لحم) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Meat Pizza (جبن مع لحم) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Meat Pizza (جبن مع لحم) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Meat Pizza (جبن مع لحم) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Chicken Pizza (جبن مع دجاج) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Chicken Pizza (جبن مع دجاج) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Chicken Pizza (جبن مع دجاج) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Chicken Pizza (جبن مع دجاج) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Hotdog Pizza (جبن مع نقانق) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Hotdog Pizza (جبن مع نقانق) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Hotdog Pizza (جبن مع نقانق) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Hotdog Pizza (جبن مع نقانق) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. Pizza (جبن مع خضار) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. Pizza (جبن مع خضار) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. Pizza (جبن مع خضار) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. Pizza (جبن مع خضار) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. & Chicken Pizza (جبن مع خضار و دجاج) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. & Chicken Pizza (جبن مع خضار و دجاج) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. & Chicken Pizza (جبن مع خضار و دجاج) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese & Veg. & Chicken Pizza (جبن مع خضار و دجاج) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Vegetables Pizza (خضار) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Vegetables Pizza (خضار) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Vegetables Pizza (خضار) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Vegetables Pizza (خضار) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Shrimp Pizza (روبيان) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Shrimp Pizza (روبيان) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Shrimp Pizza (روبيان) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Shrimp Pizza (روبيان) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Chicken Pizza (دجاج) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Chicken Pizza (دجاج) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Chicken Pizza (دجاج) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Chicken Pizza (دجاج) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pepperoni Pizza (بيبروني) - Large',  @PizzaId, N'Pizza Large', 36.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pepperoni Pizza (بيبروني) - Medium',  @PizzaId, N'Pizza Medium', 31.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pepperoni Pizza (بيبروني) - Small',  @PizzaId, N'Pizza Small', 26.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pepperoni Pizza (بيبروني) - XSmall',  @PizzaId, N'Pizza XS', 10.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),

    /* ---- Shakhtoura (شختورة) ---- */
    (N'Meat Shakhtoura (لحم)',  @ShakhtouraId, N'Shakhtoura', 9.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Shakhtoura (جبن)',  @ShakhtouraId, N'Shakhtoura', 9.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Zater Shakhtoura (زعتر)',  @ShakhtouraId, N'Shakhtoura', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Muhamar Shakhtoura (محمر)',  @ShakhtouraId, N'Shakhtoura', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Sabanek Shakhtoura (سبانخ)',  @ShakhtouraId, N'Shakhtoura', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labneh Shakhtoura (لبنة)',  @ShakhtouraId, N'Shakhtoura', 8.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Mix Shakhtoura (مكس)',  @ShakhtouraId, N'Shakhtoura', 9.50, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),

    /* ---- Farshouha (فرشوحة) ---- */
    (N'Meat Farshouha (لحم)',  @FarshouhaId, N'Farshouha', 17.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cheese Farshouha (جبن)',  @FarshouhaId, N'Farshouha', 17.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Zater Farshouha (زعتر)',  @FarshouhaId, N'Farshouha', 17.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Muhamar Farshouha (محمر)',  @FarshouhaId, N'Farshouha', 17.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Sabanek Farshouha (سبانخ)',  @FarshouhaId, N'Farshouha', 17.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Labneh Farshouha (لبنة)',  @FarshouhaId, N'Farshouha', 17.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Mix Farshouha (مكس)',  @FarshouhaId, N'Farshouha', 18.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),

    /* ---- Juices (عصائر) ---- */
    (N'Orange Juice (برتقال) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Orange Juice (برتقال) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Orange Juice (برتقال) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Mango Juice (مانجو) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Mango Juice (مانجو) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Mango Juice (مانجو) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pomegranate Juice (رمان) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pomegranate Juice (رمان) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Pomegranate Juice (رمان) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Strawberry Juice (فراولة) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Strawberry Juice (فراولة) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Strawberry Juice (فراولة) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Lemon Juice (ليمون) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Lemon Juice (ليمون) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Lemon Juice (ليمون) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Lemon with Mint Juice (ليمون و نعناع) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Lemon with Mint Juice (ليمون و نعناع) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Lemon with Mint Juice (ليمون و نعناع) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cocktail Juice (كوكتيل) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cocktail Juice (كوكتيل) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Cocktail Juice (كوكتيل) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Avocado Juice (افوكادو) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Avocado Juice (افوكادو) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Avocado Juice (افوكادو) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Apple Juice (تفاح) - Large',  @JuicesId2, N'Juice Large', 25.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Apple Juice (تفاح) - Medium',  @JuicesId2, N'Juice Medium', 11.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Apple Juice (تفاح) - Small',  @JuicesId2, N'Juice Small', 8.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Soft Drinks (غازيات)',  @JuicesId2, N'Soft Drinks', 4.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Melco (ملكو)',  @JuicesId2, N'Melco', 2.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1),
    (N'Water (ماء)',  @JuicesId2, N'Water', 1.00, (SELECT TaxRateId FROM TaxRates WHERE Name = 'Standard'), 1);
GO
